### ISSUE TITLE
观看笔记 - Pluralsight - Python for Maya Fundamentals | FXTD-Odyssey

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [FXTD-ODYSSEY/FXTD-odyssey.github.io#47]
https://fxtd-odyssey.github.io/post/13d1de85.html 

 极力推荐Maya Python入门的教程

**Comment by xbxcw** [comment]
你好大佬，按vscode 设置完之后，random 模块提示找不到了，

**Comment by xbxcw** [comment]
看完了，感谢大佬0.0

**Comment by MickyLin** [comment]
你好~
看了你的博客很受用
不过我有一些问题想请教
 
1.据我了解,如果是执行VsCode的python脚本的话,可以在maya的python脚本输入以下指令
import 脚本名
reload(脚本名)
脚本名.方法

2.如果是执行VsCode的Mel脚本的话,可以在maya的Mel脚本输入以下指令
rehash;
eval("source 脚本名.mel");

3.我的问题是,请问在VsCode里面,如何把python code或是Mel code送到 maya做测试?
只单独选几行,然后送到maya去打印数值


我有尝试安装Vscode提供的一些Extension plugin ,例如SendtoMaya 或者是Mayaport,
有按照上面提供的方法做设定去开启mayaport
但是每当按快速键把部分code送到maya时,Vscode总提示说 "command 'extension.sendMelToMaya' not found 或者是
 "command 'extension.sendPythonToMaya' not found
这个困扰我很久
不知你是否有遇过?
 
感谢回覆

**Comment by zhuruifeng-rig** [comment]
写的确实挺好，但是哔哩哔哩的教程都没有字幕，请问可以解决吗？
毕竟英语水平不行

**Comment by FXTD-ODYSSEY** [comment]
抱歉，最近整理评论才发现大家的评论。
由于之前博客优化的问题，导致部分评论链接失效了，也就看不到了_(:з」∠)_
当前 issue 将会关闭。

**Comment by FXTD-ODYSSEY** [comment]
> 你好~
> 看了你的博客很受用
> 不过我有一些问题想请教
>  
> 1.据我了解,如果是执行VsCode的python脚本的话,可以在maya的python脚本输入以下指令
> import 脚本名
> reload(脚本名)
> 脚本名.方法
> 
> 2.如果是执行VsCode的Mel脚本的话,可以在maya的Mel脚本输入以下指令
> rehash;
> eval("source 脚本名.mel");
> 
> 3.我的问题是,请问在VsCode里面,如何把python code或是Mel code送到 maya做测试?
> 只单独选几行,然后送到maya去打印数值
> 
> 我有尝试安装Vscode提供的一些Extension plugin ,例如SendtoMaya 或者是Mayaport,
> 有按照上面提供的方法做设定去开启mayaport
> 但是每当按快速键把部分code送到maya时,Vscode总提示说 "command 'extension.sendMelToMaya' not found 或者是
>  "command 'extension.sendPythonToMaya' not found
> 这个困扰我很久
> 不知你是否有遇过?
> 
> 感谢回覆

这个大概是插件问题吧，你可以重装 extension 试试，或者使用 MayaCode 插件
